spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book:social_network
    username: username
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgres
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    mail:
      host: localhost
      port: 1025
      username: ali
      password: ali
      properties:
        mail:
          smtp:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 1A49EDC8B4C2882566F6E744C9D3F
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088